FROM ghcr.io/nvidia/jax:equinox-2026-03-12

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN python -m pip install -r requirements.txt 

COPY ./experiments /app/experiments
COPY ./tests /app/tests
ENV PYTHONPATH=/app

RUN apt-get update && apt-get install -y --no-install-recommends fonts-cmu \
    && rm -rf /var/lib/apt/lists/*

COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
RUN chown -R 1000:1000 /app
USER 1000:1000

ENTRYPOINT ["/app/entrypoint.sh"]