FROM ghcr.io/nvidia/jax:equinox

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN python -m pip install -r requirements.txt 

COPY ./experiments /app/experiments
COPY ./tests /app/tests
ENV PYTHONPATH=/app

COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Try to solve file permissions issues
USER 1000:1000
ENTRYPOINT ["/app/entrypoint.sh"]